name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e14cbdc958ddead96184330